version: "1.0"
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    environment:
      - TZ=US/Pacific
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=15
    ports:
      - 7811:4444
    shm_size: 2gb